name: Archive C1 outputs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir numpy==1.26.4 matplotlib==3.8.4 networkx==3.2.1

      - name: Show installed packages (debug)
        run: pip freeze

      - name: Run mini smoke (N-P struct)
        run: |
          python scripts/run_C1_NP_min.py
          python scripts/plot_C1_2_min.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: c1-toy-artifacts
          path: |
            outputs/C1/metrics.json
            figs/C1/fig_C1_2.svg
